/** @format */
import type { Metadata } from "next";
import "./globals.css";
import Navbar2 from "@/components/ui/navbar2";
// import { FloatingNav } from "@/components/ui/floating-navbar";

import {ShowReel } from "@/components/ui/ShowReel"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <FloatingNav /> */}

        <div className="h-[150vh] relative ">
          <Navbar2 />

          {children}


          <ShowReel/>
        </div>
      </body>
    </html>
  );
}
